schema_version: 1

context:
  name: azure-mgmt-recoveryservices
  version: "3.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 7f2db98401708cf145322f50bc491caf7967bec4af3bf7b0984b9f07d3092687

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - isodate >=0.6.1
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2

tests:
  - python:
      imports:
        - azure.mgmt.recoveryservices
        - azure.mgmt.recoveryservices.aio
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure Recovery Services Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
